# ============================================================
# Inventory File — update with your EC2 instance details
# ============================================================

[wordpress]
wordpress-server ansible_host=YOUR-IP-ADDRESS

[wordpress:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
